[project]
name = "jutulgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jutuldarcy>=1.1.0",
    "langgraph>=0.5.0",
    "langsmith>=0.4.4",
]
